[build]
  base = "frontend"
  command = "CI=false npm run build"
  publish = "build"
  ignore = "git diff --quiet HEAD^ HEAD ../../frontend/"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  CI = "false"
  # Disable secrets scanning for REACT_APP_API_URL
  SECRETS_SCAN_OMIT_KEYS = "REACT_APP_API_URL"

# Redirects for Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Not found page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for images
[[headers]]
  for = "*.{png,jpg,jpeg,gif,svg,webp}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 