name: text-to-image-backend
services:
  - name: backend
    build:
      dockerfile: Dockerfile
    ports:
      - port: 5000
        protocol: http
    env:
      - name: PORT
        value: "5000"
      - name: NODE_ENV
        value: "production"
      - name: STABILITY_API_KEY
        secret: stability-api-key
      - name: OPENAI_API_KEY
        secret: openai-api-key
    health:
      http:
        path: /
      initialDelay: 30s
      interval: 15s
      timeout: 10s
      retries: 3 